apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-poc
  name: k8s-poc-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-poc
    step: {{ .Values.global.step }}
  type: NodePort
status:
  loadBalancer: {}
